### ISSUE TITLE
The identifier `type` still confuses things

### ISSUE THREAD

**Issue by thofma** [JuliaEditorSupport/julia-vim#159]
I have updated julia-vim, but `type` still confuses things:

<a href="https://imgbb.com/"><img src="https://image.ibb.co/khpgrp/2018_09_25_160629_165x166_scrot.png" alt="2018_09_25_160629_165x166_scrot" border="0"></a>

**Comment by carlobaldassi** [comment]
Thanks. I have disabled `type` entirely when using version 1.1. It still causes the same issues with version 1.0 because that's considered to be the same as 0.7 by the plugin, and in 0.7 `type` is still a block keyword, although deprecated. So maybe just use e.g. `let g:default_julia_version = "1.1"`.

**Comment by thofma** [comment]
I see. Thanks for the quick fix and the explanation.
