### ISSUE TITLE
Error message in Neovim terminal

### ISSUE THREAD

**Issue by mancellin** [JuliaEditorSupport/julia-vim#160]
Hi,

Thank you very much for your work on this plugin!

I am trying on this plugin with Neovim and I get the following error message when I run a Julia file in a Neovim terminal:
```
function <SNR>38_cursor_moved :
line    1 :
E121: Undefined variable: b:jlblk_inwrapper
```

To reproduce: open a Julia file with Neovim (can be empty) and then run the command `:term julia file.jl`.

Note that it does not happen when I open the terminal without opening a Julia file first, nor when I run something else in a terminal after reading a Julia file.
Turning off the block detection (`let g:julia_blocks=0`) also solves the problem.

**Comment by carlobaldassi** [comment]
Thanks. The issue was that the buffer name ended in `.jl` and this was associated to some autocommands, which in turn however were assuming that a julia file was being edited. But `term` does not load the plugin files, and this resulted in the errors you saw.

Accoding to my (limited) testing, this issue is now fixed, but it's entirely possible that something else will come up, please keep the reports coming in such case.
