### ISSUE TITLE
LaTeX-to-Unicode: bug in Windows 10

### ISSUE THREAD

**Issue by AlexisRenchon** [JuliaEditorSupport/julia-vim#184]
I have the exact same problem than if I use Julia in a windows command prompt terminal: 

If I type \theta + tab in windows command prompt, or in vim, I will get a symbol ¿ instead of the actual θ. 

If I open julia or vim in mintty, or git bash, I can type \theta + tab and I will get θ.

**Comment by carlobaldassi** [comment]
From what you describe, I would guess the problem is most likely with the terminal itself, either its Unicode support or the font that it uses. Did you try copy-and-pasting the theta from a terminal where it works to the one where it doesn't? If the problem persists, what about changing the font to one with good Unicode support (e.g. DejaVu Mono)?

**Comment by AlexisRenchon** [comment]
Hi Carlobaldassi, 
You're correct: it is a terminal issue (bad Unicode support, it is not the font). 
Thanks!
