### ISSUE TITLE
Adding new syntax highlighting elements

### ISSUE THREAD

**Issue by paniash** [JuliaEditorSupport/julia-vim#226]
Hi!

I'm trying to add syntax highlight elements for standard function calls, user-defined functions and user-defined function calls. I'm new to making syntax files for vim and would love some pointers. Thanks!

**For reference:** The top code is julia and the bottom one is python (notice the different shades of green while defining `mandelbrot(a)` and while calling it, also standard functions like `print()` and `abs()` are colored orange. I would like a similar behaviour with julia-vim's syntax file)

![pic-selected-210120-1953-31](https://user-images.githubusercontent.com/59497618/105188201-a5fd7400-5b59-11eb-876e-317958a1920e.png)

**Comment by carlobaldassi** [comment]
Function definitions are now highlighted. Highlighting function calls might get in in #231.
As for built-in functions, I'm generally opposed to the idea of highlighting them since there are [so many](https://github.com/JuliaLang/julia/blob/master/base/exports.jl), and (differently from Python) they don't have any special status in Julia.
