### ISSUE TITLE
More colors

### ISSUE THREAD

**Issue by felixjung** [JuliaEditorSupport/julia-vim#24]
Hi,

in my terminal vim, julia code looks rather dull:
![screen shot 2014-06-19 at 10 52 42](https://cloud.githubusercontent.com/assets/265947/3325459/26b9a374-f78f-11e3-9c2c-998e402d1485.png)

Variable names, function names, and operators are all grey. In addition only types included in Base appear to be recognised. For example, Array is highlighted as a type in yellow. DataArray, on the other hand, is not.

Are these things part of the julia-vim plugin? To me it looks like the plugin's syntax definitions need to be smarter about identifying meaningful bits of code and distinguishing them.

**Comment by rafaqz** [comment]
+1 Nvim R highlights commas and all bracket types in red. I find it helps parsing blocks of otherwise white text. Would be great if this plugin did the same.

**Comment by carlobaldassi** [comment]
Note that brackets highlighting is disabled by default, but you can use something like this to enable it:
```vim
:hi link juliaParDelim Delimiter
```
(this would use the `Delimiter` color specified by your colorscheme.)

An analogous option can be used for `juliaSemicolon` (e.g. linking it to `Operator`), and I have just added another one for `juliaComma`. If you want red commas and to override your colorscheme, you could do something like this
```vim
:hi juliaComma guifg=Red ctermfg=Red
```

**Comment by rafaqz** [comment]
Thanks!

**Comment by tomchor** [comment]
I've noticed that so far by default the functions aren't being highlighted (or maybe it's just me?) but I feel like some functions in the base are useful enough that they should. Some examples that pop into my mind are `include`, `println`, `enumerate` (and I'm sure there are more).

The fortran and python highlighting schemes (and probably others) use a very soft green color for the basis functions. It doesn't distract or pollute, but it is, in my opinion, nice to the eyes and helpful when coding. Based on that I'm thinking that it would be better if we started highlighting the functions on the base.

Any thoughts?

**Comment by KadeG** [comment]
+1 More thorough highlighting would be great.

**Comment by carlobaldassi** [comment]
That would highlight every function definition and call (so not only a few important ones as was suggested above), It is doable. But no other language plugin that I know of does that.
(Yes, all highlighting is pattern-based, the file where the patterns are specified for julia is [this one](https://github.com/JuliaEditorSupport/julia-vim/blob/4593c8b1ffe20022677e524487c8554d96cf8f84/syntax/julia.vim)).

**Comment by KadeG** [comment]
To be clear, my ideal would be to replicate [OhMYREPL.jl](https://github.com/KristofferC/OhMyREPL.jl)'s style. If I can figure out what's going on in the Vim script, I'll try to push OhMyREPL-esk options. Any hints on where to start with the function/call pattern?

**Comment by briochemc** [comment]
@carlobaldassi I see now that not coloring functions was the intended behavior, but I also see that I am not the only one wanting more colors... Would it be possible to add an option to highlight those?

You mentioned that 
> It is doable. But no other language plugin that I know of does that.

But as I was googling for a vim plugin that would highlight Julia functions, I saw that there was a vim plugin that highlights C++ functions [here](https://github.com/octol/vim-cpp-enhanced-highlight). *[Disclaimer: I have not tried it, but the screenshots seem to show what color fans like me are looking for.]* Maybe someone could somehow replicate this for Julia functions? (I personally have no clue how to edit julia-vim to do that.)

**Comment by carlobaldassi** [comment]
@jessebett some of the dullness in your vim screenshot is due to your colorscheme, at least the operators should be highlighted. It's also possible to highlight the parentheses by an option (see the docs).

As for making things similar to OhMyREPL: there is a fundamental difference between the way that works and the vim plugin, since OhMyREPL has access to a running Julia version, can use a full-fledged Julia parser, and recognize on the fly what each syntax element is. The vim plugin on the other hand cannot, for example, recognize that something is a user-defined type, it can only recognize the types it knows about.

As for highlighting functions, again it's doable (probably) purely by syntactic inspection, by checking whether an identifier is followed by an open parenthesis (with an optional preceding dot). Note that there is no reasonable sure way that we can discriminate between function declaration and function call though. Anyway one problem with this is that Julia is very permissive with identifier names and that creates some serious performance issues which I'm not sure how to address exactly (the plugin is already quite slow as-is).

**Comment by jessebett** [comment]
@carlobaldassi Thanks for your response. I do know that the colour schemes are responsible for the different colours, this post was just to draw the attention to the highlighting itself.

I also appreciate that OhMyREPL does get privileged access to the syntax in a way vim does not. However, do you know if this is also true for the syntax highlighter used by Juno in Atom? Because, for example, it can highlight user defined types.

Actually, discriminating between function declaration and call isn't even consistent in OhMyREPL. for example defining functions inline `myfun(x) = x.a` would highlight as a call.

However, at least with user defined types it should be possible to syntax after `::` and around `<:` right?
And for function definitions and calls before `()` and `.()`.

No idea about speed, however.

**Comment by KristofferC** [comment]
> Actually, discriminating between function declaration and call isn't even consistent in OhMyREPL. for example defining functions inline myfun(x) = x.a would highlight as a call.

Yes, I didn't add the distinction for the short form of function declarations yet.

**Comment by del2z** [comment]
A simple solution for highlighting functions is putting codes in ~/.vim/after/syntax/julia.vim
```
syntax cluster  juliaParScope           contains=@juliaParItems,juliaParBlockInRange
syntax cluster  juliaBlockScope         contains=@juliaBlocksItems,juliaConditionalEIBlock,juliaConditionalEBlock
syntax cluster  juliaTotalScope         contains=@juliaParScope,@juliaMacroItems,@juliaBlockScope
syntax match    juliaFunction           display "\<[a-z_][a-zA-Z0-9_]*\>!\?\.\?("me=e-1 containedin=@juliaTotalScope
hi def link     juliaFunction           Function
```
Most function names are highlighted except in a macro line. And I cannot figure out why this doesn't work. Need improvements.

**Comment by tomchor** [comment]
Just dropping to check if there are any improvements to this. I came back to `julia-vim` after 2 years and it looks exactly the same to me. It would indeed be nice to make some `OhMyREPL` color schemes available such as @KadeG suggested.

**Comment by carlobaldassi** [comment]
I don't think there's anything more to do here after #231.
We are now highlighting:
* blocks and keywords
* built-in constants
* symbols and quoted expressions
* all operators (including ternary and ranges, with special parsing within square brackets of `begin` and `end`)
* types (both built-in and valid identifiers in type expressions)
* macros
* numbers
* characters, special characters, strings and docstrings (you can link `juliaDocString` to distinguish them from regular strings)
* commands
* comments
* some syntax errors
* function definitions (in `function` blocks)
* function calls (optionally)
* brackets, commas, semicolons (optionally)

If you don't see some of these as colored, either see the docs (for the optional ones) or change your colorscheme.

I think it's unlikely that it is possible to reasonably detect function definitions given in assignment form, so for now they will (optionally) stay highlighted as function calls.
I also don't think functions from Base can reasonably be highlighted.

**Comment by tomchor** [comment]
> We are now highlighting:
blocks and keywords
built-in constants
symbols and quoted expressions
all operators (including ternary and ranges, with special parsing within square brackets of begin and end)
types (both built-in and valid identifiers in type expressions)
macros
numbers
characters, special characters, strings and docstrings (you can link juliaDocString to distinguish them from regular strings)
commands
comments
some syntax errors
function definitions (in function blocks)
function calls (optionally)
brackets, commas, semicolons (optionally)


Thanks! I appreciate the effort.
