### ISSUE TITLE
missing dictionary key in call to `L2U_SetFallbackMapping`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaEditorSupport/julia-vim#301]
Apparently `L2U_SetFallbackMapping` is sometimes being called when there is no `rhs` key in the `mmdict` dictionary.  I'm getting
```
Error detected while processing InsertEnter Autocommands for "*"..function LaTeXtoUnicode#Init[14]..<SNR>22_L2U_SetAutoSub[15]..<SNR>22_L2U_SetFallbackMapping:
line    6:
E716: Key not present in Dictionary: "rhs"
```

At least I thought that's what was happening... I tried putting in
```vimscript
  if !has_key(mmdict, "rhs")
      return mmdict
  endif
```
but the behavior is exactly the same.

I still am unable to identify exactly what circumstance is causing this error.

**Comment by TheCedarPrince** [comment]
I am also having this issue! Thought I was crazy @ExpandingMan - thanks for opening this. Will be using your branch until merge. :)

**Comment by usmcamp0811** [comment]
Yea I am having the same problems.. when it happens, whenever I hit `<CR>` in insert mode I pastes `<91>L2UFallbackCR`... its supper duper annoying..

**Comment by ExpandingMan** [comment]
Seems the maintainers are MIA, maybe we should ask around slack...

**Comment by carlobaldassi** [comment]
From what I can tell, this should only arise as the result of having mapped <CR> to an empty action.
However, this is the only mentions of such thing I could find in the docs:
```
						*map_empty_rhs* *map-empty-rhs*
You can create an empty {rhs} by typing nothing after a single CTRL-V (you
have to type CTRL-V two times).  Unfortunately, you cannot do this in a vimrc
file.
							|<Nop>|
An easier way to get a mapping that doesn't produce anything, is to use
"<Nop>" for the {rhs}.  For example, to disable function key 8:
	:map  <F8>  <Nop>
	:map! <F8>  <Nop>
```
I couldn't reproduce the first method, and with the second one `maparg` just returns a dict with the key `"rhs"` associated to `"<Nop>"`.
So I'm still not sure about how the error occurred (assuming it's not fixed, hopefully).

@ExpandingMan maybe you could disable the julia-vim plugin and check the output of `:echo maparg('<CR>', 'i', 0, 1)` and see if it returns a dict without the 'rhs' key? And it that's the case what is setting it (and how/why)?

**Comment by TheCedarPrince** [comment]
Hey @carlobaldassi , thanks for getting back to us about this! So far no issues since the merge.

When I run the `:echo maparg('<CR>', 'i', 0, 1)` command, I see the following:

```lua
{'lnum': 0, 'script': 0, 'desc': 'cmp.utils.keymap.set_map', 'callback': 116, 'noremap': 1, 'lhs': '<CR>', 'mode': 'i', 'nowait': 0, 'expr': 0, 'sid': -8, 'buffer': 0, 'silent': 1}
```

Here is the output when I disable julia-vim:

```lua
{'lnum': 0, 'script': 0, 'desc': 'cmp.utils.keymap.set_map', 'callback': 152, 'noremap': 1, 'lhs': '<CR>', 'mode': 'i', 'nowait': 0, 'expr': 0, 'sid': -8, 'buffer': 0, 'silent': 1}
```

If I am right, seems like the `rhs` value is mapped somewhere then - correct?

**Comment by carlobaldassi** [comment]
Thanks @TheCedarPrince. So what I see here is that `<CR>` is mapped but it doesn't have a `'rhs'`. I also see some stuff (like the `'desc'` and `'callback'` keys) that is not mentioned in the [docs](https://neovim.io/doc/user/builtin.html).
I suppose this is a very recent version of neovim?
Anyway my guess at this point is that `cmp.utils.keymap.set_map` is somehow associating a callback to `<CR>`. Ideally, julia-vim should support this as a fallback, since after the merge of #302 it will simply override it. Any PR for this would be welcome.

In any case, at least with julia-vim active, but only *after* you have entered insert mode at least once in the buffer, you should see a 'rhs' field.
